# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zachary R. Wu Hankinson
email: zacharywuhankinson@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hello world. This site is a work in progress. Please excuse the mess.
baseurl: /docs/ # the subpath of your site, e.g. /blog
url: https://zacharywuhankinson.github.io # the base hostname & protocol for your site, e.g. http://example.com
repository: zacharywuhankinson/zacharywuhankinson.github.io
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
# remote_theme: pages-themes/primer@v0.6.0 # pretty basic, but it works
# remote_theme: pages-themes/slate@v0.2.0 # only has the default layout, which is annoying
# theme: just-the-docs # works, is good, should probably use
# theme: minimal-mistakes-jekyll # seems to only have the default layout...
remote_theme: mmistakes/so-simple-theme@3.2.0 # ngl I really like this one. I might use it. It doesn't have the automatic sitemapping built in, but maybe we can add that...
# theme: minima # the default, pretty basic
# theme: jekyll-theme-primer # works
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

include:
  - README.md
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
